# Generated by Django 4.2.13 on 2024-06-17 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('inn', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('Не в работе', 'Не в работе'), ('В работе', 'В работе'), ('Отказ', 'Отказ'), ('Сделка закрыта', 'Сделка закрыта')], default='Не в работе', max_length=20)),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
