# Generated by Django 4.2.13 on 2024-06-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='patronymic',
            new_name='middle_name',
        ),
    ]
